### PR TITLE
Upgrade Twig from 1.0 to 3.0, again

### PR DESCRIPTION
**Pull request by tortuetorche**
But now it works 🥳

**Fix Laravel 8 dependencies with PHP 8.0**

Related to: #18

### CODE REVIEW

**Comment by tortuetorche** [comment]
Hi @Olofguard,

Any news to merge this pull request?

By the way I send few pull request to this repository, which are merged and I'm glad you accept them 👍
So, is it possible to add me as a _Member_, please?
Then I could directly merge pull requests from me or other contributors.

Have a good day,
Tortue Torche

**Comment by tortuetorche** [comment]
Hi again @Olofguard,

Did you considered my proposition from [my last message](https://github.com/generationtux/php-healthz/pull/24#issuecomment-764672440), to help you maintaining this repository?

Have a good day,
Tortue Torche

**Comment by tortuetorche** [comment]
Hi @Olofguard,

I don't want to spam you, but do you want some help to maintain this repository?
Of course I can fork it, but It'll be more advice to keep only one repository for this very useful PHP package 👍

Have a good day,
Tortue Torche

**Comment by Olofguard** [comment]
Sorry for the delayed response. A lot going on a gentux and not a lot of hands to deal with it all. Though we appreciate the offer, we prefer to maintain this package ourselves as we have so many services that utilize it. If that decision changes we'll reach out to you. 

Feel free to continue to contribute to the repository as you have. All of you contributions have been much appreciated!

Cheers 🍻 ,
Olofguard

**Review by Olofguard — APPROVED** [review]

**Pull request merged**
