### PR TITLE
PHP 7.2 and 8.0 support 🚀 and Laravel 6.0 support

### PR DESCRIPTION
**Pull request by tortuetorche**
Support PHP from 7.2 to 8.0 and also Laravel 6.0 (because it's the current LTS version) to 8.0

Reference: https://laravel.com/docs/8.x/releases#support-policy

### CODE REVIEW

**Comment by tortuetorche** [comment]
Build passed: https://travis-ci.org/github/generationtux/php-healthz/builds/728988669

**Comment by Olofguard** [comment]
Sorry just saw this and https://github.com/generationtux/php-healthz/pull/19 I'll work on getting this out. Would you mind resolving the conflict here?

**Comment by tortuetorche** [comment]
> Sorry just saw this and #19 I'll work on getting this out. Would you mind resolving the conflict here?

Done!

Build passed: https://travis-ci.org/github/generationtux/php-healthz/builds/739553581

**Comment by tortuetorche** [comment]
Hi @Olofguard,

Can you review this pull request, please?

Have a good day,
Tortue Torche

**Comment by tortuetorche** [comment]
PHP 8.0 support 🚀!

Build passed: https://travis-ci.org/github/generationtux/php-healthz/builds/746731953

By the way, you should [migrate](https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide/) from the legacy https://travis-ci.org to the new https://travis-ci.com, to get faster builds 👍
I did it for my repositories, it's like night and day 😆

Have a good day,
Tortue Torche

**Review by Olofguard — APPROVED** [review]

**Pull request merged**
